// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6gxHDchyue7l8H0Na8EJReIzl98SqUc',
    appId: '1:992284120956:web:0d7e4a644cc4aa2a11b6f9',
    messagingSenderId: '992284120956',
    projectId: 'connectxregtration',
    authDomain: 'connectxregtration.firebaseapp.com',
    storageBucket: 'connectxregtration.firebasestorage.app',
    measurementId: 'G-4KKCWHE9MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI31r6d6Z0zXNHcQ2q38QjMDdY9bzClPI',
    appId: '1:992284120956:android:0d53f222353df70411b6f9',
    messagingSenderId: '992284120956',
    projectId: 'connectxregtration',
    storageBucket: 'connectxregtration.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7oBoMZObiahA24Z28baG_nrZZA3wEVGU',
    appId: '1:992284120956:ios:8d99d5c80818586a11b6f9',
    messagingSenderId: '992284120956',
    projectId: 'connectxregtration',
    storageBucket: 'connectxregtration.firebasestorage.app',
    iosBundleId: 'com.example.connectxHr',
  );
}
